### ISSUE TITLE
Allow ([...]) syntax in match patterns

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/felix#104]
e.g.

```
match ([1, 2, 3]) with
| ([1, 2, 3]) =>
    // ...
endmatch;
```

**Comment by kirbyfan64** [comment]
~~I swear the assignment was Skaller's idea~~

**Comment by gbluma** [comment]
Sure. I'll take a look.

Just as a heads up, I think we'll also get the following as a byproduct

```
match ([1,2,3,4,5]) with
| ([1,2,3,x]) => // 'x' = [4,5]
endmatch;
```

**Comment by skaller** [comment]
Well I'm not so sure that would be right. There is already an operator ,,  for which this might be more correct. That's a tuple cons operator for tacking a head element onto a tuple. And that already pattern matches tuples. So it would be more like

```
| ([1,2,3,,x]) => ...
```

which is row polymorphism for tuples. See the end of src/packages/core_type_constructors.fdoc for the file tuple.flx. I find this stuff is not a good as I'd like due to the lack of "output" or "associated" types in type classes. This applies even to the polymorphic recursion you see in the examples. It only works if the result type is invariant, eg "string" for str, or "bool" for total order comparison. What is you see in the file is roughly the result of compiler supported GADTs specific to tuples.

**Comment by gbluma** [comment]
Okay, syntax like this is working now.
```
println$
    match ([1,2,4]) with
    | [1,2,3+1] => "Yes"
    | _ => "No"
    endmatch;
```

I think this might be a bit of a hacky solution because it hooks into the evaluation process but wraps the expression in "list()." There could be some performance problems if this isn't lifted out of the pattern match, but we'll worry about that later.

The above is the same as the following:

```
println$
    match ([1,2,4]) with
    | $( (1,2,3+1).list ) => "Yes"
    | _ => "No"
    endmatch;
```

**Comment by skaller** [comment]
Ah, I see. That was not what I expected. The problem with your solution is that the "list" cannot actually contain pattern variables: its an expression. 

What I thought was that you'd use Scheme to process a list of pattern expressions, and replace it with Cons (pattern, Cons (pattern . ... in which case the entries in the list are actually patterns. The macro "nos" is useful here, it allows a Scheme string to become a Felix identifier. The macro "noi" allows a Scheme identifier to become a Felix identifier. Felix identifiers in the Scheme context are actual S-expressions themselves.

**Comment by gbluma** [comment]
Right. I'm falling back on the existing tuple parsing in the expression syntax. I would prefer to actually decode the List into it's constituent Cons elements and recur the pattern matching, but that means re-writing some of the tuple parsing bits, and I hit a snag.

**Comment by skaller** [comment]
You can do it later than the parser if that's convenient. It's certainly easier to process terms in Ocaml than Scheme. However you have to then add transient terms into the expression ast and perhaps more and then add prints for them and add assert falses everywhere you could get one but its supposed to be gone. Its not clear which is the most painful :)

The Scheme processing leaves the compiler untouched, it can also be completely isolated from everything else but Scheme is really a very bad functional language: no pattern matching. Still this one should be relatively easy: you get a Scheme list and just fold it by plugging Cons in front. Or a Snoc. Or you may have to reverse the list first.

This is how ! is handled:

```
  private scons_pattern := stuple_cons_pattern "!" scons_pattern =>#
    '''`(pat_nonconst_ctor ,_sr ,(nos "Cons") (pat_tuple ,_sr (,_1 ,_3)))''';
  private scons_pattern := stuple_cons_pattern =># "_1";
```

so all you really need is that, except with "," instead of "!". That means you need different  precedences than the above.

Another way is to copy this one:

```
  //$ Match a tuple with 2 or more components.
  private stuple_pattern := scoercive_pattern ("," scoercive_pattern )* =>#
    "(chain 'pat_tuple _1 _2)";
```

and change the name to pat_list, again, get the precedences right.
Then you have to modify flx_desugar/flx_sex2flx in the compiler instead.

One way i do this is force the terms to be atomic so you initially have to put parens around each term or it won't work, and then relax the precedences after it flows through the compiler correctly.

**Comment by gbluma** [comment]
We can now bind variables using the list syntax.

(1) Exact matching doesn't require closing the list with `Empty`
```
var mylist = list[int](1,2,3);
println$
  match mylist with
  | [1,2,3] => "matched exact"
  endmatch;
```

(2) We can split the list with double commas. That is, the parser matches element by element on the lft hand side of the double-comma, and the right had side allows for capturing the "rest of the list."
```
println$
  match mylist with
  | [1,,i] => i.str  // i = list(2,3)
  endmatch;
```

(3) Just as an interesting example, we can bind multiple variables interposed with constants. It works!
```
println$
  match mylist with
  | [i,2,j] => i.str + "-" + j.str   // i=1,j=3
  endmatch;
```

(4) Empty lists are also handled. 
```
var mylist2 = list[int]();
println$
  match mylist2 with
  | [] => "empty list"
  endmatch;
```

**Comment by kirbyfan64** [comment]
YESSS!! Thanks so much!!

**Comment by skaller** [comment]
> On 21 Oct. 2017, at 06:28, Garrett Bluma <notifications@github.com> wrote:
> 
> We can now bind variables using the list syntax.
> 
> (1) Exact matching doesn't require closing the list with Empty
> 
> var mylist = list[int](1,2,3);
> println$
>   match mylist with
>   | [1,2,3] => "matched exact"
>   endmatch;

What about

	[solo] 

?

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by gbluma** [comment]
You mean like this?
```
 var mylist = list[int](1);
 println$
   match mylist with
   | [1] => "matched exact"
   endmatch;
```

already handles it. Likewise for single element variable binding.

**Comment by skaller** [comment]
Could this have interfered with lists in expressions? 
The build of flx is now broken with my (uncommitted) changes.

    var STDIMPORTS=(["plat/flx.flxh", "concordance/concordance.flxh"]);

    control.STDIMPORTS <- list[string]();

        IMPORTS = control.STDIMPORTS + control.IMPORTS,

[flx_bind/flx_lookup.ml:2973: E149] [lookup_name_with_sig] Can't find +[] of BTYP_tuple(BTYP_inst(13142[BTYP_array(BTYP_inst(15938[]),2)]),BTYP_inst(13142[BTYP_inst(15938[])]))=
+[] of list[string^2] * list[string]
In /Users/skaller/felix/src/packages/flx.fdoc: line 2207, cols 19 to 55
2206:         AUTOMATON = control.AUTOMATON,
2207:         IMPORTS = control.STDIMPORTS + control.IMPORTS,
                        *************************************
2208:         FLXLIBS = dvars.FLX_STD_LIBS,


Felix seems to think control.STDIMPORTS has type list[string^2].
This would happen if the precedence of the list constructor items

	([ .. ])

changed. It doesn’t seem to have anything to do with the changes I’m making.
It is possible. We have

typedef control_type = typeof (#dflt_control);

on line #771. 

fun dflt_control () =>
  struct {
……

—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by gbluma** [comment]
> Could this have interfered with lists in expressions?

I don't think so. It's scoped inside the pattern match expressions as a sub-grammar of `spattern`. I don't see how that could affect the grammar for general expressions.
