### ISSUE TITLE
Performance of Axiom verification?

### ISSUE THREAD

**Issue by sighoya** [felix-lang/felix#114]
@skaller wrote:
>This particular type class is not good, because it does not specify any semantics. There should REALLY be axioms that say that applying next or get is only meaningful if atend is not true.

I'am with you with semantic specifications. But are semantic specifications easily verifiable?
IMHO, if you define laws for an operator/function which operates on the instance of a typeclass, then the law has to be checked for all values of that instance. 
For example: Int implementing Eq[Int], then reflexivity, symmetry and transitivity has to be verified/checked for all values in Int for each function/operator parameter which is of type Int and also for the values of the types of the other parameters which should slow down the compiler, right?
How is this implemented in Felix?

**Comment by skaller** [comment]
Originally there were two mechanism. The first was to translate the axioms into the syntax for the Why automatic theorem prover, and submit them to it for verification. I got this to work for one axiom but it was hard! Mainly because there are a lot of hidden assumptions.

The second method was an axiom_check operator. This was a run time check. You would say:

```
axiom_check (v1, v2);
```

for example, and it pattern matched ALL the axioms against the type of v1 and v2, and then executed them. Typically you'd put that statement in a loop to obtain coverage. I used this to verify the laws of arithmetic for Floating numbers and discovered that the associative law does not actually hold! It hold for real numbers but not floating approximations, which lead me to split the float interface into two part: Dring (division ring) and FloatDring (approximate reals). 

However there was a problem with this axiom_check that it could "overselect" and get some unintended axioms leading to an infinite loop so I disabled it. The plan was to do it again but also throw in the name of the axiom to be checked but I never got around to it.

There's another problem with it as well. Originally, Felix did everything polymorphically. The code was only monomorphised in the back end. However I changed that to monomorphise earlier to simplify some of the algorithms. Monomorphisation works by following an instantiation path from specified root functions (the mainline, and any exported functions). Unfortunately that path doesn't grab applicable axions. Reductions suffered the same fate.

So to monomorphise the axiom checks they have to call specific axioms, a second reason
to modify the implementation to do that.

**Comment by sighoya** [comment]
Thanks for the answer, skaller. 
I think, too the compiler should not check axioms as this would require large compile times. Especially, if one updates the source file and want to compile quickly the changes.

As you aid, the other problem is that the axioms do not hold for approximations of arbitrary number types. Maybe, when the limit of a certain value range for a type is exceeded, then a special symbol could be given back instead.
For example, one could say that a:Float64=1e-64/2 is the limit symbol eps instead of zero such that the axiom checker ignores all verifications with such limit symbols.
However, I don't know if this makes the type system in other areas unsound.

**Comment by skaller** [comment]
IEEE has axioms but they're very complicated. Also note Felix only supports *first order* logic in axioms and many axioms are second order.

**Comment by skaller** [comment]
Note, currently, axiom testing is disabled. When nested parameter lists were introduced the requisite modifications to axioms and reductions were bypassed to reduce the amount of work required. Aka I'm lazy! The axiom testing machinery has to be revisited anyhow. Reductions are harder because I don't know how to monomorphism them. We can easily retain monomorphic reductions.

**Comment by skaller** [comment]
Axiom checking is currently disabled due to a change in the way parameters are specified, in particular, nested tuples are allowed. Due to laziness I have not changed the axiom checks to conform.

I think I will just make axioms ordinary executable functions, with somewhat specialised syntax, to resolve this issue. However the topic regards verification, and all attempts to connect to an external theorem prover have been abandoned so I'm closing this issue.
