### ISSUE TITLE
The links to the documentation are broken on the main page

### ISSUE THREAD

**Issue by mrakgr** [felix-lang/felix#116]
[Here.](https://github.com/felix-lang/felix#bindings)

**Comment by skaller** [comment]
> On 14 Jul. 2018, at 21:47, Marko Grdinić <notifications@github.com> wrote:
> 
> Here.

Yes they are. We no longer have a website.
And the PDF got moved.

Try this:

https://felix-documentation-master.readthedocs.io/en/latest/masterdirectory.html

I’m working on this:

http://felix.readthedocs.io/en/latest/

It is lacking quite a bit: expressions, statements not done yet.

User tool guide:

https://felix-tools.readthedocs.io/en/latest/flx.html


—
John Skaller
skaller@internode.on.net

**Comment by skaller** [comment]
There's now an "under construction" page at 

http://felix-lang.github.io/felix/

I hope most references to the old website are gone. It's unfortunate but the original documentation required the flx_web web server to display correctly, and that isn't available except on a real or virtual machine which is no longer available due to lack of funding.
