### ISSUE TITLE
Getting SDL to work

### ISSUE THREAD

**Issue by skaller** [felix-lang/felix#134]
See also #133 and #125.

On Linux, these fixed repository files are installed:

```
~/felix>ls src/config/linux
demux.fpc	pthread.fpc	sdl2_image.fpc
flx.flxh	sdl2.fpc	sdl2_ttf.fpc
```

with
```
~/felix>cat src/config/linux/sdl2.fpc
Generated_from: 3643 "/Users/skaller/felix/src/packages/sdl.fdoc"
Name: SDL2
Description: Simple Direct Media Layer 2.0
cflags: -I/usr/local/include/SDL2
includes: '"SDL.h"'
provides_dlib: -L/usr/local/lib -lSDL2
provides_slib: -L/usr/local/lib -lSDL2
```

On at least Debian, this information could be wrong, it might be installed in /usr/lib, not /usr/local/lib.

The formula to fix this is:

Step 1. Copy the relevant files into $HOME/.felix/config
Step 2. Edit them so they're correct.
Step 3. Copy them to build/release/host/config

Next time you rebuild Felix, the contents of src/config/linux are copied
into build/release/config *and then* the contents of $HOME/.felix/config are copied 
into build/release/config, clobbering the hard coded defaults in the repository.

You actually need SDL2, SDL2_ttf, SDL2_Image, and SDL2_gfx, and any other SDL2
libraries could be useful. I forget exactly which ones have. You need the
*development versions*, that is, including the header files.

Felix has a half-built GUI which is based on a Felix binding to SDL2
which requires the above libraries.  There are some tests of the GUI
in the standard test suite.

**Comment by Rencer** [comment]
Thanks for the response and the quick fix, but still have problems.

Like I said I don't really understand this whole compiling from source, I just followed what is written in the README.md how to compile it on Linux.
I need Felix just to compile a program that is written in Felix.

Because the previous attempt to compile it is failed, I just deleted everything, and "git-clone"-ed it again.
When I navigate into the "felix" folder where the source is saved and I do the "ls src/config/linux" command it said there is no such file or directory. I checked it in my file manager and ideed there is no such directory as "config" within the "src" folder. So those files are missing hence I can't copy them.
The "cat src/config/linux/sdl2.fpc" doesn't work too, again I get the no such file or directory error.

I using Manjaro Linux and that is not Debian, it is build on Arch.
I don't understand what the Step 2. "Edit them so they're correct." means. What I need to edit and how? Or where I can find those files so I can copy them into one of those folders?

I hope you can help me, I really appreciate if you can help a simple user like me.
Thanks all the effort.

**Comment by skaller** [comment]
Inactive.

**Comment by Rencer** [comment]
I really appreciate your help, but I find an alternative to the program, what is written in Felix.
So I don't need Felix anymore, sorry.

But it is really good to see that you give all the help you can!
It is a rare thing, (or at least this is my experince) that someone here in GitHub give this much help for a simple user, who doesn't knows the technical bacground of how compiling works, just follows the instructions.
THANKS!
