### ISSUE TITLE
How to read user input?

### ISSUE THREAD

**Issue by enty8080** [felix-lang/felix#146]
Like in C++ cin

**Comment by skaller** [comment]
Here'a simple example:

```
print "Enter name 1 : ";
var name = readln stdin; // felix stdin
println$ "Your name is " + name;

print "Enter name 2 : ";
var name2 = readln cstdin; // C stdin
println$ "Your name is " + name2;

write (stdout, "Enter name 3 : "); // felix stdout
var name3 = readln stdin; // felix stdin
writeln (cstdout, "Your name is " + name3);

```

Felix has three variables for `stdin`, `stdout`, and `stderr` which are initially set to `cstdin`, `cstdout` and `cstderr` respectively. These are C `FILE*` types. You cannot redirect the C ones, but you can redirect the Felix ones by simply assigning another value to them.

```
var filename = "fred.tmp";
var file = fopen_output_text filename;
stdout = file;

write (stdout, "Into a file we go\n");
fclose file;

var x = load filename;
print x;
```

Perhaps unfortunately, `print` and `println` go to `cstdout` so can't be redirected. I think I did this so that Felix could generate plain C functions that didn't depend at all on the Felix run time.

**Comment by skaller** [comment]
I think this is also a good question. The "simple I/O" system is in src/packages/io.fdoc which is not actually all that simple in terms of the implementation. By "simple" it means, there is no error checking.

**Comment by enty8080** [comment]
Do you know how to compile Felix for windows on linux?

**Comment by skaller** [comment]
I can be done but it is tricky and depends on exactly what you need.

Method 1, you just set the macros to WINDOWS, run Felix to make WIndows C++, then ship the sources to Windows and run MSVC++ to make the binaries. This doesn't make much sense to do by hand, you could just run Felix on Windows. However if you're using a Continuous Integration Server and want to edit and test code on Linux, and then send generated C++ off to the server to generate the Windows code it does.

Method 2, you use a  cross compiler available on Linux to make a static linked Windows executable. You could make a DLL but that would require the Felix run time built on Windows. C++ code built with either g++ or clang for Windows will still not be compatible with Windows C++ DLLs on Windows built with MSVC++, they should link against C code though. Felix exports are extern "C" however if you export a C++ type you'd be in trouble.

If you look in `GNUmakefile`, there is code to build the target `gcc_macosx`:

```
gcc_macosx:
	# =========================================================
	# prepare for gcc build on macosx
	# =========================================================
	${BUILDBIN}/flx_build_prep --target-dir=${BUILDROOT}		\
		--target-bin=gcc_macosx --source-dir=${BUILDROOT}	\
		--source-bin=host --clean-target-bin-dir --copy-compiler\
	       	--configure --compiler=gcc --os=macosx --bits=64	\
		--cxx-compiler=g++ --debug

	# =========================================================
	# build gcc rtl on macosx
	# =========================================================
	${LPATH}=${BUILDROOT}/host/lib/rtl flx_build_rtl --target-dir=${BUILDROOT} --target-bin=gcc_macosx

	# =========================================================
	# build Felix with gcc rtl on macosx
	# =========================================================
	${LPATH}=${BUILDROOT}/host/lib/rtl flx_build_boot --target-dir=${BUILDROOT} --target-bin=gcc_macosx --build-all

```

You would need to modify that to build say `gcc_windows`, and change the name of the compiler to the gcc cross compiler. There's another method where you set the full path name to the compiler.

However you may have to do some hand editing after the first step. This file needs to be changed:

**Comment by skaller** [comment]
BTW: after doing all that this should work in theory:

```
flx --target=gcc_windows -static -c -od WindowsCode .....
```

The `-c` is to stop the process trying to run the windows code on Linux. Then you have to find the executable produced in directory WindowsCode and copy it to Windows to run it. I'd be amazed if you can get this to work. It will probably take weeks to sort out, but it can be done. A slightly better way would include building a toolchain object for gcc_windows instead of just changing the name of the compiler. This can be set to give exactly the right switches to the cross compiler. That requires copying an existing toolchain source, and compiling it on Linux, then making it the toolchain to use for the `gcc_windows` target. Felix comes with toolchains for MacOS and Linux for both gcc and clang, and on Windows for MSVC++, but there's no cross compilation toolchain. The Felix command line doesn't accept all switches.

You can also do what my friend is doing building for iPhone on MacOS: write your own build script which invokes the Felix compiler "flxg" directly, bypassing "flx" driver. 

Felix is a cross-cross compiler, so there are two translation steps: Felix to C++ and C++ to binary. Almost all Felix code is universal in that it generates C++ that is platform independent. But not all of it. Some of the Felix code has to have conditional compilation to generate the right C++, which is what the macro settings shown in the previous post do. Stuff like sockets is just different on Windows, so even though the Felix code *using* sockets is the same on all platforms, the binding code to make that platform independent is not. In fact the bindings for sockets aren't complete, so `flx_web`, the webserver, which does run on Windows, has some conditional compilation in it, because the socket I/O libraries don't have completely platform independent bindings.
