### ISSUE TITLE
Building error in Fedora32

### ISSUE THREAD

**Issue by orz--** [felix-lang/felix#153]
# ============================================================
#
# CONFIGURING FELIX
#
#   See build/release/fbuild.log for full transcript
#
# ============================================================
#
python3 fbuild/fbuild-light configure --buildroot=build 
configuring build phase
configuring host phase
using build's c and cxx compiler
checking ocamlc.opt version : 4.10.0
checking if ocamlc.opt can make objects : ocamlc.opt compiler failed
make: *** [GNUmakefile:116: configure] Error 1

build/release/fbuild.log recorded following.

checking if ocamlc.opt can make objects : 
MainThread: starting '/usr/bin/ocamlc.opt -c -I build/release -unsafe-string -w yzex -warn-error FPSU -o build/release/temp.cmo build/release/temp.ml'
 * ocamlc.opt                           : build/release/temp.ml -> build/release/temp.cmo
 + /usr/bin/ocamlc.opt -c -I build/release -unsafe-string -w yzex -warn-error FPSU -o build/release/temp.cmo build/release/temp.ml
/usr/bin/ocamlc.opt: OCaml has been configured with -force-safe-string: -unsafe-string is not available.

There are no "-unsafe-string" options in ocaml4.10.0, I think.
Where doing correct, does compilation pass?

**Comment by skaller** [comment]
You will need to use an earlier version of Ocaml. I'll explain the reason below. 

If you are using Fedora package manager, uninstall Ocaml.
Now, install opam. Opam allows you to have multiple versions of Ocaml installed.
There is a command to switch between versions. I am using 4.06 so I know that works.
You can also install 4.10. To build Felix, switch to 4.06, then run the build.
You can switch back afterwards. Ocaml is only needed to build the compiler.

Sorry about the hassle, blame the Ocaml team for making a serious mess with a
sequence of poor decisions which destroyed backwards compatibility.

Now the reason. Felix used two third party packages and one no longer supported
Ocaml system package. Felix uses Dypgen as its parser, and OCScheme for the parser
actions. Neither of these is maintained any more. In addition, Felix used BigNum,
which has been dropped as a supported package.

I have modified Felix to remove the need for BigNum. This unfortunately required
wiping out half the R5RS Scheme support OCScheme provided. it was fully compliant,
but I had to chop out all the math support except small integers. Also Felix used
BigNum internally for integers, I had to replace them as well.

Secondly, Dypgen used mutable strings. I have fixed all of the Dypgen Library.
However I have not been able to fix the parser generator tool "dypgen".
The original clean code was modified with hackery by the author to insert
`#line` lines so that errors reflect back to the original source if the source
is generated. This was done by somehow hacking the parser buffer.
I just couldn't figure out how to fix it. Ocaml team didn't help by not
providing a parser buffer that could use mutable and immutable store.

So, the -unsafe-string option is required, just to build the dypgen parser generator.
It's not actually required in the Felix compiler. The parser in Felix is very simple
and fairly fixed, because it is actually only used to parse the grammar, which
is then used to dynamically extend the parser (with caching).  

Unfortunately Dypgen is hard to replace. Its the most advanced parser available
anywhere in any language. It's a GLR parser with extensions, using an SLR kernel,
which can be extended by adding new productions are run time. This causes the
parser kernel to be rebuilt on the fly. Felix uses that, so the Felix grammar is actually
in the Felix library, it's ordinary Felix code. You can even add grammar productions
in the middle of a construct or at the top of a file.  Beat ordinary macro processing!

Note also, Ocaml versions have deprecated and/or removed library functions.
Again this is a pain because some functions are available in later versions
but not earlier and vice versa. Since Ocaml team refuses to support Windows
but that's a requirement, I have, with help from others, had to build a binary Ocaml
for Windows. It's a real pain to build, and it happens to be a version that works with
the -unsafe-string option. I don't want to have to mess about building yet another
Windows version. 

So the Ocaml version required for Felix is locked in to a window approximately
4.05 through 4.09 or something, until the dypgen problem is fixed (which may
not happen any time soon).

**Comment by orz--** [comment]
Thank you very much for polite explanation.
I understood it's necessary to use a OPAM manager.
I'll try it.
