### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by 3oheicrw** [felix-lang/felix#173]
If needed I could install a POSIX shell like Cygwin or MSYS2.

**Comment by 3oheicrw** [comment]
It seems MSVC is required.

**Comment by skaller** [comment]
Yes, Felix supports Windows at the moment only for MSVC. It only uses the command line tools which are freely available. You also need to build latest Ocaml 4.14 which is a real pain. Unfortunately whilst I have a Windows box I cannot connect it to the Internet at the moment so I cannot provide any direct support for the Windows build.

However you can build Felix under Bash for Windows, that is, by installing Ubuntu on Windows. However the graphics uses SDL2 will require an X-Windows server. Native Windows graphics requires the MSVC build.

Felix used to build under Cygwin64 and it may build using gcc or clang based Windows systems, I don't know. Certainly a toolchain could be developed for these but again, I can't do it at the moment. 

Ideally Felix should build under Microsofts CI building system which is integrated with GitHub but I couldn't get the C++ tools to install which is weird considering MSVC is a Microsoft product. But it is what it is. The Linux build still runs on Travis.

**Comment by 3oheicrw** [comment]
> Felix used to build under Cygwin64

This is no longer the case. I tried with Cygwin64 and it failed after the build started a while (note: the build process is awfully slow!)

**Comment by skaller** [comment]
The build process is slow the first time because it builds everything twice: first it builds a bootstrap version (using Python), then uses the bootstrap version to build the real version (using Felix). Then it runs the whole test suite.

I can't help with a Cygwin64 failure without knowing how it failed. Even then it may be tricky since I cannot get hold of the most recent version of Felix on my Windows box (nor export it to the repository). This is because I use my iPhone as a wifi provider and whilst my Mac and Android phone connect to it fine, my Windows box will not: I think it's a bug in the iPhone since the Windows box connects just fine to other wifi services. Unfortunately I cannot afford the second account i would need to connect a wifi modem to my ISP.

In any case the main support is for MSVC since you have to use that to interface to C++ DLLs.  It should actually be possible to build using Ubuntu for Windows and then rebuild for MSVC++ (from Ubuntu)  but again, I cannot experiment on how to setup the toolchain.
