### ISSUE TITLE
Quiet option to avoid displaying felixboot messages

### ISSUE THREAD

**Issue by razetime** [felix-lang/felix#174]
The basic `flx` script running command always outputs the following before the program's output:
```
BOOTFLX
[bootflx] flx
```
I would like to suggest an option `-q` or `--quiet` since I want to pipe output from my felix scripts to other commands/files in my shell.

**Comment by skaller** [comment]
no it doesn't, that's only the bootstrap version. If you're getting that you aren't running the full version.
```
~/felix>flx hello
Hello World!
```

**Comment by skaller** [comment]
Looking at your build problem in the email, the full version of flx is not being built. For some reason the linker is requiring a relocation stub whilst the build process is deliberately NOT using -fPIC to produce position independent code because that requires extra instructions and uses a machine register which non-PIC code does not. So non-PIC code executes faster.

**Comment by skaller** [comment]
https://www.collabora.com/about-us/blog/2014/10/01/dynamic-relocs,-runtime-overflows-and-fpic/

**Comment by skaller** [comment]
So roughly the problem is that I have no idea .. and the diagnostics from the linker do not help at all .. determine which particular object file is causing the error. Either that of the link command is incorrect and isn't telling the linker to do static linkage correctly. If all the files are non-PIC and the link is static this error cannot arise.. The only problem is that the C library might be relocatable but that would mean ALL C modules would require -fPIC in which case there'd be no point in the switch at all.

**Comment by razetime** [comment]
Thanks for the clarification. Moving conversation over to #175.
