### ISSUE TITLE
Issues with `raise`

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/felix#71]
[This code](https://gist.github.com/kirbyfan64/3ca06336634f8fa19d9e):

```
fun add_to(totals: list[float])(values: list[float]) =>
    if values.len != 1.size then let n = totals.len in match n with
    | 0uz => values
    | $(values.len) => take n.int $ (add of (float^2)).map $ totals.zip2 values
    // this ugliness is because of a bug in Felix that generates invalid C++ code
    | _ => #(fun () = { raise "Inconsistent-length rows"; return #list[float]; })
    endmatch else totals;

fun add_line_to(totals: list[float])(line: string) =>
    totals.add_to $ (float of string).map $ split (line.strip, ',');

fun sum_file(filename: string) =>
    add_line_to.fold_left #list[float] $ split (filename.load, '\n');

proc sum_and_print_file(filename: string) {
    res := (str of float).map $ sum_file filename;
    println $ fold_left (fun (a:string)(b:string) => a+","+b) res.head res.tail;
}

match #System::args with
| Cons (_, Cons (filename, Empty)) => sum_and_print_file filename;
| _ => raise "Exactly 1 filename must be given";
endmatch;
```

has a line that says:

```
    // this ugliness is because of a bug in Felix that generates invalid C++ code
    | _ => #(fun () = { raise "Inconsistent-length rows"; return #list[float]; })
```

If I change it to:

```
    | _ => raise "Inconsistent-length rows"
```

I get:

```
Converting return of 'any' type to procedure call
In file included from /home/ryan/stuff/.felix/text/home/ryan/golf/four_ml/felix.cpp:6:
/home/ryan/stuff/.felix/text/home/ryan/golf/four_ml/felix.hpp:580:8: fatal error: 
      field has incomplete type 'void'
  void _genout_urv68201;
       ^
1 error generated.
C++ compilation /home/ryan/stuff/.felix/text/home/ryan/golf/four_ml/felix.cpp failed
[flx] C++ compilation /home/ryan/stuff/.felix/text/home/ryan/golf/four_ml/felix.cpp failed
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

The code snippet:

``` c++
struct add_to_uncurry {
  FLX_FMEM_DECL

  void _genout_urv68201;
  void _genout_urv68136;
  void _genout_urv68062;
  void _genout_urv68011;
  void _genout_urv67960;
  void _genout_urv67921;
  void _genout_urv67878;
  void* _i68193_v68193_t;
  _at68570 _i68192_v68192_h;
```

An attempt to reproduce it with a smaller program:

```
fun x() => raise "abc!";
x;
```

made the compiler crash:

```
Fatal error: exception File "src/compiler/flx_cpp_backend/flx_cal_type_offsets.ml", line 206, characters 29-35: Assertion failed
Felix compilation "/media/ryan/stuff/felix/build/release/host/bin/flxg" "-q" "--inline=25" "--output_dir=/media/ryan/stuff/.felix/cache" "--cache_dir=/media/ryan/stuff/.felix/cache" "-I/media/ryan/stuff/felix/build/release/share/lib" "-I/media/ryan/stuff/felix/build/release/host/lib" "--syntax=@/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files" "--automaton=/media/ryan/stuff/.felix/cache/media/ryan/stuff/felix/build/release/share/lib/grammar/grammar.files/syntax.automaton" "--import=plat/flx.flxh" "std" "/home/ryan/golf/four_ml/cg.flx" failed
Error 1 in flx: [strerror_r] Failed to find text for error number 1
```

**Comment by skaller** [comment]
There is indeed an issue in the unification engine.

The idea is that this type:

	type any = any;

or alternatively:

	type any = x as x;

should unify with any type, since every type T satisfies the defining equation

	T = T

Then functions like exit would have type int->any. In a match

	match x with
	| 1 => 2
	| 2 => exit (0)
	endmatch

it should be ok because "any" unifies with "int", so the type of the match is just "int".
Note that type any is just a fixpoint of itself, that is its like a pointer that points to itself
(at the type level).

However you cannot actually have values of type any. Some theorists say a
non-returning function should have type void=0 (the type with no values).
So code like:

	var x = #{ raise "fred" };

is never going to work, raise can ONLY be used in a match where an actual
real value of some definite type is returned.

This is in the library:

src/lib/std/program/system.flx:  gen exit: int -> any = '::std::exit($1)' requires Cxx_headers::cstdlib;

but there is a special hack: if a function call returns "any" it is "treated like a procedure".
So you can do

	exit 0;

and it will work, because it is treated "as if" it read exit: int -> 0.

This i not really correct. The right idea is that 0 returns control but
no value, whereas any doesn't return control at all. So it can be used
in a context where any other value is required, because it will never
return the wrong value (because it never returns at all :)

Any (sic) how .. its all a bit of a mess.

--
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by kirbyfan64** [comment]
Well, maybe, along with `any`, there could be a `noreturn` type. It'd be treated just like `any`, but it can be used anywhere and replaced with some filler value based on the caller's *real* return type.

**Comment by skaller** [comment]
On 15/05/2015, at 11:51 AM, Ryan Gonzalez wrote:

> Well, maybe, along with any, there could be a noreturn type.

How would this help?

> It'd be treated just like any, but it can be used anywhere and replaced with some filler value based on the caller's real return type.

But that's exactly what unification does. Any unifies with T to produce T.

The problem is that a *function* returning any could be used like:

	var x = exit 0;

and now we have a variable of type any. Although it never gets a value,
the variable may still exist unless steps are taken to eliminate it.

Similarly consider:

	var x = exit 0, 1;

so now what is the type of x? Is it any * int?

This is serious! With eager evaluation, tuples aren't real products.
With lazy evaluation, we might still fetch x.1 (the int). With indeterminate
evaluation its even trickier :)

--
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by kirbyfan64** [comment]
The compiler would know that `noreturn` never...returns, so it could use filler values (`*static_CAST<T*>(NULL)`) without worrying about anything else.

**Comment by skaller** [comment]
On 16/05/2015, at 3:49 AM, Ryan Gonzalez wrote:

> The compiler would know that noreturn never...returns, so it could use filler values (*static_CAST<T*>(NULL)) without worrying about anything else.

Where does it get the T from?

Do you mean this on std/control/control.flx?

 //$ throw[ret, exn] throw exception of type exn
  //$ in a context expecting type ret. It can only be
  //$ used in an expecting context such as the argument
  //$ of a function return or handler of a match expression.
  //$ Felix does not check the ret type, since it sees 
  //$ the type is 'any'. The generated C++, however, will
  //$ fail if the wrong type is used.
  gen throw[ret,exn] : exn -> any = "(throw $1,*(?1*)0)";

which does what you said? Except, you have to tell it the T (ret) type.

--
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by kirbyfan64** [comment]
No. I was just using it as an example of a filler that Felix could use with some type that shows that the function never returns.

Of course, that code would crash, but the noreturn type would symbolize that it doesn't matter.

**Comment by skaller** [comment]
On 16/05/2015, at 3:11 PM, Ryan Gonzalez wrote:

> No. I was just using it as an example of a filler that Felix could use with some type that shows that the function never returns.
> 
> Of course, that code would crash, but the noreturn type would symbolize that it doesn't matter.

Sure but that's exactly what type any means.
It is used in the library. The problem is something like:

	var x = 1, f ();

where f() doesn't return. This is a problem with products when using eager
evaluation. The usual tuple is NOT a proper product.

There is a similar problem with sums with lazy evaluation.
In Haskell too. They're NOT proper sums.

You can see if the product is lazily evaluated then the first
component will be 1, the second component can't be fetched
because trying will cause an escape. But with eager evaluation,
the first component doesn't exist either because evaluating
the product escapes.

Now, if you say

	var x = f();

where f() is type any (never returns) the compiler just makes a variable
of type any, which causes things to barf. This doesn't arise *returning* any
if there is a second branch of a match/conditional with a definite type,
because unification just selects that type:

	var x = match a with | 1 => 1 | 2 -> f() endmatch; // type int

The reason is, that's a match, that is, its a sum type. So when we
execute f() it throws and the assignment to x never happens so its
ok that x have type int.

AFAICS Felix handles this correctly, but not the product case, and not
a single assignment either (probably for much the same reason).

The point is: it's not good enough to just delete variable x

	var x = f();

because what about

	var x = 1, f();

??

Well we can delete that too but what about

	val x = 1, f();

Can we delete that? Are you SURE???

	var y = x.0; // x.1 is never used ...

That will optimise probably to

	var y = (1, f()).0;

and then to

	var y = 1;

that is, Felix can do lazy product evaluation. It just doesn't have to.
If we delete x, what happens to the calculation of y?
	
--
john skaller
skaller@users.sourceforge.net
http://felix-lang.org
